---
services:
  my-app:
    image: my-app:${TAG-latest}
    restart: always
    environment:
    - LOG_SEVERITY=INFO
    healthcheck:
      test:
      - CMD
      - python
      - -c
      - import urllib.request; urllib.request.urlopen('http://localhost:8080/api/v1/healthcheck/liveness').read()
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
    - 8080:8080
    build:
      context: .
