---
name: Test Docker Compose
on:
  pull_request:
    types:
    - opened
    - synchronize
jobs:
  test-docker-compose:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Run Docker Compose tests
      run: ./scripts/test-docker-compose.sh
